person/urls.py
from django.urls import path
from . import views

app_name = 'person'
urlpatterns = [
    path('', views.PersonMain.as_view(), name='index'),
    path('create/', views.PersonCreate.as_view(), name='create'),
    path('<int:pk>/update/', views.PersonUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.PersonDelete.as_view(), name='delete'),
]

ticsocial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    # APP
    path('', include('person.urls'))
]

person/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Person(AbstractUser):
    birthday = models.DateField(auto_now=False, auto_created=False, blank=True, null=True)
    id_type = models.CharField('ID Type', max_length=150,  blank=True, null=True)
    id_number = models.IntegerField('ID Number', default=0)

person/forms.py
from django.forms import ModelForm
from .models import Person

# Create the form class.
class PersonForm(ModelForm):
    class Meta:
        model = Person
        fields = (
            'first_name',
            'last_name',
            'id_type',
            'id_number',
            'birthday',
            'username',
            'password',
            'is_active',
        )

person/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .forms import PersonForm
from .models import Person

# Create your views here.
class PersonMain(LoginRequiredMixin, View) :
    def get(self, request):
        list_objects = Person.objects.filter(is_active=True).order_by('first_name')
        count = list_objects.count()

        ctx = {'person_count': count, 'person_list': list_objects}
        return render(request, 'person/person_list.html', ctx)

class PersonCreate(LoginRequiredMixin, CreateView):
    model = Person
    form_class = PersonForm
    success_url = reverse_lazy('person:index')


class PersonUpdate(LoginRequiredMixin, UpdateView):
    model = Person
    form_class = PersonForm
    success_url = reverse_lazy('person:index')


class PersonDelete(LoginRequiredMixin, DeleteView):
    model = Person
    success_url = reverse_lazy('person:index')

person/templates/person/person_confirm_delete.html
{% block content %}

<h1>Delete Person</h1>

<p>Are you sure you want to delete the person: {{ person }}?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
    <input type="submit" onclick="window.location='{% url 'person:index' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

person/templates/person/person_form.html
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
        <input type="submit" onclick="window.location='{% url 'person:index' %}' ; return false;" value="Cancel">
    </form>
{% endblock %}

person/templates/person/person_list.html
{% block content %}
    <h1>Person List</h1>
    {% if person_list %}
        <ul>
            {% for person in person_list %}
              <li>
                  {{ person.username }}
                  (<a href="{% url 'person:update' person.id %}">Update</a> |
                    <a href="{% url 'person:delete' person.id %}">Delete</a>) <br/>
              </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no persons in the list.</p>
    {% endif %}


    <p>
        The number of person is: {{ person_count }}
    </p>

    <p>
        <a href="{% url 'person:create' %}">Add Person</a>
    </p>


{% endblock %}